#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 SHUMA ITO
# SPDX-Licence-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
    try: 
        ans += int(line)
    except:
        ans += float(line)
print(ans)

